-- AlterTable
ALTER TABLE `Product` ADD COLUMN `brandId` INTEGER NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE `Product` ADD CONSTRAINT `Product_brandId_fkey` FOREIGN KEY (`brandId`) REFERENCES `IBrand`(`brandId`) ON DELETE RESTRICT ON UPDATE CASCADE;
